- name: default value 
  hosts: localhost
  tasks:
  - name: print default value 
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"
    
- name: upper case
  hosts: localhost
  vars:
    greetings: "Hello, good morning"
  tasks:
  - name: convert to upper case
    ansible.builtin.debug:
      msg: "{{ greetings | upper }}"

- name: lower case
  hosts: localhost
  vars:
    greetings: "Hello, good morning"
  tasks:
  - name: convert to upper case
    ansible.builtin.debug:
      msg: "{{ greetings | lower }}"

- name: Demo on loops
  hosts: localhost
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }}"
    loops:
    - linux
    - shell
    - ansible