- name: Install packages 
  hosts: web
  become: yes
  tasks:
  - name: Installinglist of packages 
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest 
    loop:
    - { name: 'nginx', state: 'absent' } 
    - { name: 'mysql', state: 'absent' }
    
